### ISSUE TITLE
Overflow property doesn't work on mobile

### ISSUE THREAD

**Issue by jaspervd** [jaspervd/thanks-for-the-fish#3]
On mobile the `overflow` property doesn't work, the user can both scroll horizontally and vertically which is not ideal.

**Comment by codinsonn** [comment]
Using overflow: hidden + viewport config might help
http://stackoverflow.com/questions/18268300/overflowhidden-not-working-on-mobile-browser

**Comment by jaspervd** [comment]
Tried it but alas it didn't work!

**Comment by jaspervd** [comment]
Fixed!
Thanks to: http://stackoverflow.com/questions/14270084/overflow-xhidden-doesnt-prevent-content-from-overflowing-in-mobile-browsers
